---
- name: nopcommerce
  hosts: localhost
  become: yes
  tasks:
    - name: Regesiter microsoft key
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /home/ubuntu/packages-microsoft-prod.deb
    - name: Add Microsoft package repository
      ansible.builtin.shell:
        cmd: "sudo dpkg -i /home/ubuntu/packages-microsoft-prod.deb"
    - name: Update package lists
      ansible.builtin.apt:
        update_cache: yes
    - name: add dotnet
      ansible.builtin.apt:
        name: dotnet-sdk-7.0 
        state: present
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: Start service 
      ansible.builtin.service:
        name: nginx
        state: started
    - name: copy default
      ansible.builtin.copy:
        src: "default"
        dest: "/etc/nginx/sites-available/default"
    - name: Change file ownership group and permissions
      ansible.builtin.file:
          path: /var/www/nopCommerce
          state: directory
    - name: Download nopcommerce
      ansible.builtin.get_url:
        url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.5/nopCommerce_4.60.5_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce/nopCommerce_4.60.3_NoSource_linux_x64.zip
    - name: install unzip
      ansible.builtin.apt:
        name: unzip
        state: present
    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: /var/www/nopCommerce/nopCommerce_4.60.3_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce/
        remote_src: yes    
    - name: Create a directory bin
      ansible.builtin.file:
          path: /var/www/nopCommerce/bin
          state: directory
    - name: Create a directory logs
      ansible.builtin.file:
          path: /var/www/nopCommerce/logs
          state: directory 
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /var/www/nopCommerce
        owner: www-data
        group: www-data
        recurse: true
    - name: copy the servicefile
      ansible.builtin.copy:
        src: "nopCommerce.service"
        dest: "/etc/systemd/system/nopCommerce.service"  
    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: nopCommerce.service
        state: started
    - name: Restart network service for interface eth0
      ansible.builtin.service:
        name: nginx
        state: restarted
